<Gerenciador>:
    Home:
    Ideias
    Historico:
    Aparelhos:
    Geladeira:
    Ventilador:

<Home>:
    name: "home"

    MDBoxLayout:
        orientation: "vertical"
        spacing: 8

        canvas.before:
            Color:
                rgba: 1,1,1,1
            Rectangle:
                pos: self.pos
                size: self.size

        MDFloatLayout:
            size_hint_y: None
            height: 200

            Image:
                source: "images/fundo_grande.png"
                allow_stretch: False
                keep_ratio: True
                size_hint: None, None
                size: self.texture_size
                x: 0
                top: self.parent.top

            MDLabel:
                text: "Olá, Ana!"
                font_size: 20
                bold: True
                color: 0, 0, 0, 1
                size_hint: None, None
                pos_hint: {"x": 0.08, "y": 0.3}

            Button:
                background_normal: "images/bell.png"
                background_down: "images/bellpress.png"
                size_hint: None, None
                size: 20, 20
                border: 0,0,0,0
                pos_hint: {"right": 0.95, "top": 0.85}

        BoxLayout:
            orientation: "vertical"
            height: 160
            size_hint_y: None
            padding: 15

            Label:
                text: "Consumo"
                font_size: 18
                color: 0.2, 0.05, 0.18, 1
                pos_hint: {"x": -0.36, "top": 0}

            BoxLayout:
                spacing: 15
                pos_hint: {"x": 0.04, "top": 0}

                Button:
                    size_hint: None, None
                    size: 75, 75
                    background_normal: "images/aparelhos.png"
                    background_down: "images/aparelhospress.png"
                    border: 0,0,0,0
                    on_release:
                        app.root.current = "aparelhos"
                        app.root.transition.direction = "left"

                Button:
                    size_hint: None, None
                    size: 75, 75
                    background_normal: "images/historico.png"
                    background_down: "images/historicopress.png"
                    border: 0,0,0,0
                    on_release:
                        app.root.current = "historico"
                        app.root.transition.direction = "left"

        MDBoxLayout:
            orientation: "vertical"
            size_hint_y: None
            padding: [8, 18, 8, 8]
            spacing: 14
            height: 360

            MDLabel:
                size_hint_y: None
                text: "Hoje"
                height: self.texture_size[1]
                padding_x: 18
                color: 0.2, 0.05, 0.18, 1
                font_size: 18

            MDFloatLayout:
                size_hint_y: None
                height: 180

                MDCard:
                    orientation: "horizontal"
                    size_hint: .9, None
                    height: 170
                    pos_hint: {"center_x": .5, "top": 1}

                    radius: [20]
                    padding: 15
                    spacing: 15

                    md_bg_color: 0.97,0.97,0.97,1

                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 0.1

                        RoundedRectangle:
                            pos: self.x, self.y - 8
                            size: self.width, self.height
                            radius: [20]

                    MDBoxLayout:
                        orientation: "vertical"
                        size_hint_x: 0.35

                        MDLabel:
                            text: root.nivel

                            halign: "center"
                            adaptive_height: True

                            color:
                                (0.3,0.8,0.5,1) if root.nivel == "Baixo" else (1,0.7,0.2,1) if root.nivel == "Médio" else (1,0.3,0.3,1)

                        Widget:

                        FloatLayout:

                            size_hint_y: None
                            height: 120

                            canvas:

                                Color:
                                    rgba: 0.9,0.9,0.9,1

                                Line:
                                    width: 12
                                    circle: (self.center_x, self.center_y, 42)

                                Color:
                                    rgba: 0.4,0.8,0.7,1

                                Line:
                                    width: 12
                                    cap: "round"
                                    circle: (self.center_x, self.center_y, 42, 0, 360 * root.porcentagem)

                            MDLabel:
                                id: gauge_label

                                text: "0 kw/h"

                                halign: "center"

                                pos_hint: {"center_x": .5, "center_y": .5}

                                bold: True

                        Widget:

                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_x: 0.65
                        spacing: 10

                        padding: [0, 10]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "00h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra1
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.2

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "04h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra2
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.4

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "08h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra3
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.6

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "12h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra4
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.9

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "16h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra5
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.7

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

                        MDBoxLayout:
                            orientation: "vertical"

                            MDLabel:
                                font_size: 10
                                text: "20h"
                                halign: "center"
                                adaptive_height: True

                            Widget:

                            Widget:
                                id: barra6
                                size_hint_x: None
                                width: 20
                                size_hint_y: 0.5

                                canvas.before:
                                    Color:
                                        rgba: 0.4,0.8,0.7,1

                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [8]

            MDBoxLayout:
                size_hint_y: None
                height: 50
                spacing: 50
                adaptive_width: False

                Widget:

                MDIconButton:
                    icon:
                        "home" if root.manager.current == "home" else "home-outline"

                    theme_icon_color: "Custom"

                    icon_color:
                        (0.1, 0.5, 0.2, 1) if root.manager.current == "home" else (0.6, 0.6, 0.6, 1)

                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "home"

                MDIconButton:
                    icon: "lightbulb-outline"
                    pos_hint: {"center_y": .5}
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "ideias"

                MDIconButton:
                    icon: "account"
                    pos_hint: {"center_y": .5}

                Widget:

<Historico>:
    name: "historico"

    MDBoxLayout:
        orientation: "vertical"
        padding: [20,20,20,20]
        spacing: 20

        canvas.before:
            Color:
                rgba: 1,1,1,1

            Rectangle:
                pos: self.pos
                size: self.size

        MDBoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10

            MDIconButton:
                icon: "arrow-left"

                theme_icon_color: "Custom"
                icon_color: 0.2,0.05,0.18,1

                on_release:
                    app.root.current = "home"
                    app.root.transition.direction = "right"

            MDLabel:
                text: "Histórico"

                bold: True
                font_size: 24

                color: 0.2,0.05,0.18,1

        MDBoxLayout:
            spacing: 15
            size_hint_y: None
            height: 40

            MDFlatButton:
                text: "Diário"
                theme_bg_color: "Custom"

                md_bg_color:
                    (0.88,0.8,0.92,1) if root.modo == "diario" else (0.95,0.95,0.95,1)

                text_color:
                    (0.2,0.05,0.18,1)

                on_release:
                    root.carregar_diario()

            MDFlatButton:
                text: "Mensal"
                theme_bg_color: "Custom"

                md_bg_color:
                    (0.88,0.8,0.92,1) if root.modo == "mensal" else (0.95,0.95,0.95,1)

                text_color:
                    (0.2,0.05,0.18,1)

                on_release:
                    root.carregar_mensal()

            MDFlatButton:
                text: "Anual"
                theme_bg_color: "Custom"

                md_bg_color:
                    (0.88,0.8,0.92,1) if root.modo == "anual" else (0.95,0.95,0.95,1)

                text_color:
                    (0.2,0.05,0.18,1)

                on_release:
                    root.carregar_anual()

        Widget:
            size_hint_y: None
            height: 10

        MDCard:
            id: botao_data

            size_hint: None, None
            size: 110, 40

            pos_hint: {"center_x": .5}

            radius: [16]

            elevation: 0

            ripple_behavior: False

            md_bg_color: 0.87,0.95,0.9,1

            on_release:
                root.abrir_menu_data(botao_data)

            MDLabel:
                text:
                    root.dia_texto if root.modo == "diario" else root.mes_texto if root.modo == "mensal" else root.ano_texto

                halign: "center"

                bold: True

                color: 0.5,0.7,0.6,1

        FloatLayout:
            size_hint_y: None
            height: 250

            canvas:

                Color:
                    rgba: 0.85,0.9,0.88,1

                Line:
                    width: 20
                    circle:
                        (self.center_x,
                        self.center_y + 10,
                        95,
                        -90,
                        90)

                Color:
                    rgba: 0.45,0.7,0.65,1

                Line:
                    width: 20
                    circle:
                        (self.center_x,
                        self.center_y + 10,
                        95,
                        -90,
                        (-90) + (180 * root.porcentagem))

            MDLabel:
                text: str(root.consumo)

                font_size: 42
                bold: True

                halign: "center"

                color: 0.2,0.05,0.18,1

                pos_hint: {"center_x": .5, "center_y": .48}

            MDLabel:
                text: root.unidade

                font_size: 20

                halign: "center"

                color: 0.7,0.7,0.7,1

                pos_hint: {"center_x": .5, "center_y": .32}

        MDLabel:
            text:
                "" if root.modo == "diario" else "Semana 1" if root.modo == "mensal" else ""

            halign: "center"

            bold: True

            font_size: 24

            color: 0.2,0.05,0.18,1

        MDBoxLayout:
            size_hint_y: None
            height: 220
            spacing: 8
            pos_hint: {"x": -0.05}

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: None
                width: 35

                MDLabel:
                    text: "350"
                    font_size: 11
                    halign: "right"

                Widget:

                MDLabel:
                    text: "175"
                    font_size: 11
                    halign: "right"

                Widget:

                MDLabel:
                    text: "0"
                    font_size: 11
                    halign: "right"

            FloatLayout:

                canvas.before:
                    Color:
                        rgba: 0.85,0.85,0.85,1

                    Line:
                        points: [self.x, self.center_y, self.right, self.center_y]
                        width: 1

                MDBoxLayout:
                    pos_hint: {"center_x": .5, "center_y": .48}
                    spacing: 6
                    size_hint: 1, 1

                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra1

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text: "00h" if root.modo == "diario" else ("jan" if root.modo == "anual" else "dom")
                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra2

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "04h" if root.modo == "diario" else ("fev" if root.modo == "anual" else "seg")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra3

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "08h" if root.modo == "diario" else ("mar" if root.modo == "anual" else "ter")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra4

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]
                        MDLabel:
                            text:
                                "12h" if root.modo == "diario" else ("abr" if root.modo == "anual" else "qua")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra5

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]
                        MDLabel:
                            text:
                                "16h" if root.modo == "diario" else ("mai" if root.modo == "anual" else "qui")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 18
                            height: root.barra6

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]
                        MDLabel:
                            text:
                                "20h" if root.modo == "diario" else ("jun" if root.modo == "anual" else "sex")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra7

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo == "diario" else ("jul" if root.modo == "anual" else "sab")

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra8

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo != "anual" else "ago"

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra9

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo != "anual" else "set"

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra10

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo != "anual" else "out"

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra11

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo != "anual" else "nov"

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20
                    MDBoxLayout:
                        orientation: "vertical"

                        Widget:

                        Widget:
                            opacity: 1 if self.height > 0 else 0
                            size_hint: None, None
                            width: 18
                            height: root.barra12

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [5]

                        MDLabel:
                            text:
                                "" if root.modo != "anual" else "dez"

                            halign: "center"
                            font_size: 9
                            size_hint_y: None
                            height: 20


<Aparelhos>:
    name: "aparelhos"

    MDBoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: [20, 20, 20, 20]

        canvas.before:
            Color:
                rgba: 1,1,1,1
            Rectangle:
                pos: self.pos
                size: self.size

        MDBoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10

            MDIconButton:
                icon: "arrow-left"
                theme_icon_color: "Custom"
                icon_color: 0.2, 0.05, 0.18, 1

                on_release:
                    app.root.current = "home"
                    app.root.transition.direction = "right"

            MDLabel:
                text: "Aparelhos"
                bold: True
                font_size: 22
                color: 0.2, 0.05, 0.18, 1
                valign: "middle"

        Widget:
            size_hint_y: None
            height: 20

        MDLabel:
            text: "Meus aparelhos"
            bold: True
            font_size: 20
            color: 0.2, 0.05, 0.18, 1
            size_hint_y: None
            height: self.texture_size[1]

        MDGridLayout:
            cols: 2
            spacing: 20
            adaptive_height: True
            size_hint_y: None
            height: self.minimum_height

            MDCard:
                orientation: "vertical"
                radius: [22]
                ripple_behavior: True
                padding: 0
                size_hint_y: None
                height: 170

                md_bg_color: 0.97,0.97,0.97,1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.1

                    RoundedRectangle:
                        pos: self.x, self.y - 6
                        size: self.width, self.height
                        radius: [22]

                on_release:
                    app.root.current = "geladeira"
                    app.root.transition.direction = "left"

                MDBoxLayout:
                    size_hint_y: None
                    height: 60
                    padding: [18, 0, 12, 0]
                    spacing: 16

                    canvas.before:
                        Color:
                            rgba: 0.85,0.93,0.88,1

                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [22,22,0,0]

                    MDIcon:
                        icon: "fridge-outline"
                        theme_text_color: "Custom"
                        text_color: 0.5,0.75,0.65,1
                        font_size: 26

                    MDLabel:
                        text: "Geladeira"
                        color: 0.4,0.4,0.4,1

                MDBoxLayout:
                    orientation: "vertical"
                    padding: 12
                    spacing: 8

                    MDLabel:
                        text: root.status_geladeira
                        bold: True
                        font_size: 14
                        adaptive_height: True

                        color:
                            (0.3,0.8,0.5,1) if root.status_geladeira == "Ligado" else (1,0.3,0.3,1)

                    MDBoxLayout:
                        spacing: 10
                        adaptive_height: True

                        FloatLayout:
                            size_hint: None, None
                            size: 50, 50

                            canvas:

                                Color:
                                    rgba: 0.9,0.9,0.9,1

                                Line:
                                    width: 6
                                    circle: (self.center_x, self.center_y, 18)

                                Color:
                                    rgba: 0.4,0.8,0.7,1

                                Line:
                                    width: 6
                                    cap: "round"
                                    circle:
                                        (self.center_x, self.center_y, 18, 0,
                                        360 * root.porcentagem_geladeira)

                        MDLabel:
                            text: f"{root.watts_geladeira} W usados"
                            valign: "middle"
                            color: 0.4,0.4,0.4,1

            MDCard:
                orientation: "vertical"
                radius: [22]
                ripple_behavior: True
                size_hint_y: None
                height: 170

                md_bg_color: 0.97,0.97,0.97,1

                canvas.before:
                    Color:
                        rgba: 0, 0, 0, 0.1

                    RoundedRectangle:
                        pos: self.x, self.y - 6
                        size: self.width, self.height
                        radius: [22]

                on_release:
                    app.root.current = "ventilador"
                    app.root.transition.direction = "left"

                MDBoxLayout:
                    size_hint_y: None
                    height: 60
                    padding: [20, 0, 12, 0]
                    spacing: 20

                    canvas.before:
                        Color:
                            rgba: 0.85,0.93,0.88,1

                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [22,22,0,0]

                    MDIcon:
                        icon: "fan"
                        theme_text_color: "Custom"
                        text_color: 0.5,0.75,0.65,1
                        font_size: 26

                    MDLabel:
                        text: "Ventilador"
                        color: 0.4,0.4,0.4,1

                MDBoxLayout:
                    orientation: "vertical"
                    padding: 12
                    spacing: 10

                    MDLabel:
                        text: root.status_ventilador
                        bold: True
                        font_size: 14
                        adaptive_height: True

                        color:
                            (0.3,0.8,0.5,1) if root.status_ventilador == "Ligado" else (1,0.3,0.3,1)

                    MDBoxLayout:
                        spacing: 10
                        adaptive_height: True

                        FloatLayout:
                            size_hint: None, None
                            size: 50, 50

                            canvas:

                                Color:
                                    rgba: 0.9,0.9,0.9,1

                                Line:
                                    width: 6
                                    circle: (self.center_x, self.center_y, 18)

                                Color:
                                    rgba: 0.4,0.8,0.7,1

                                Line:
                                    width: 6
                                    cap: "round"
                                    circle:
                                        (self.center_x, self.center_y, 18, 0,
                                        360 * root.porcentagem_ventilador)

                        MDLabel:
                            text: f"{root.watts_ventilador} W usados"
                            valign: "middle"
                            color: 0.4,0.4,0.4,1

            MDCard:
                radius: [22]
                size_hint_y: None
                height: 170
                md_bg_color: 0.97,0.97,0.97,1

                canvas.before:
                    Color:
                        rgba: 0.85,0.93,0.88,1

                    RoundedRectangle:
                        pos: self.x, self.top - 45
                        size: self.width, 45
                        radius: [22,22,0,0]

        Widget:

        MDFloatingActionButton:
            elevation: 0
            icon: "plus"
            pos_hint: {"center_x": .88}
            md_bg_color: 0.9,0.8,0.95,1
            icon_color: 0.3,0.1,0.3,1

<Geladeira>:
    name: "geladeira"

    MDBoxLayout:
        orientation: "vertical"
        padding: [20, 20, 20, 20]
        spacing: 25

        canvas.before:
            Color:
                rgba: 1,1,1,1

            Rectangle:
                pos: self.pos
                size: self.size

        MDBoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10

            MDIconButton:
                icon: "arrow-left"

                theme_icon_color: "Custom"
                icon_color: 0.2,0.05,0.18,1

                on_release:
                    app.root.current = "aparelhos"
                    app.root.transition.direction = "right"

            MDLabel:
                text: "Geladeira"

                bold: True
                font_size: 24

                color: 0.2,0.05,0.18,1

        Widget:
            size_hint_y: None
            height: 10

        FloatLayout:
            size_hint_y: None
            height: 260
            halign: "center"

            canvas:

                Color:
                    rgba: 0.85,0.9,0.88,1

                Line:
                    width: 20
                    circle:
                        (self.center_x,
                        self.center_y + 10,
                        95,
                        -90,
                        90)

                Color:
                    rgba: 0.45,0.7,0.65,1

                Line:
                    width: 20
                    circle:
                        (self.center_x, self.center_y + 10,
                        95,
                        -90,
                        (-90) + (180 * root.porcentagem))


            MDLabel:
                text: f"{root.kw_dia}"

                font_size: 42
                bold: True
                halign: "center"

                color: 0.2,0.05,0.18,1

                pos_hint: {"center_x": .5, "center_y": .48}

            MDLabel:
                text: "kw / dia"

                font_size: 20

                halign: "center"

                color: 0.7,0.7,0.7,1

                pos_hint: {"center_x": .5, "center_y": .32}

            MDCard:
                size_hint: None, None
                size: 120, 45

                pos_hint: {"center_x": .5, "y": 0}

                radius: [16]

                md_bg_color: 0.87,0.95,0.9,1

                elevation: 0

                MDLabel:
                    text: root.data_atual

                    halign: "center"

                    bold: True

                    color: 0.5,0.7,0.6,1

        Widget:
            size_hint_y: None
            height: 10

        MDLabel:
            text: "kw / dia"

            bold: True
            font_size: 15

            color: 0.2,0.05,0.18,1

            size_hint_y: None
            height: self.texture_size[1]

        MDBoxLayout:
            size_hint_y: None
            height: 240
            spacing: 8
            padding: [0, 0, 10, 0]

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: None
                width: 35

                MDLabel:
                    text: "360"
                    font_size: 11
                    halign: "right"
                    valign: "top"

                Widget:

                MDLabel:
                    text: "180"
                    font_size: 11
                    halign: "right"
                    valign: "middle"

                Widget:

                MDLabel:
                    text: "0"
                    font_size: 11
                    halign: "right"
                    valign: "bottom"

            FloatLayout:

                canvas.before:
                    Color:
                        rgba: 0.85,0.85,0.85,1

                    Line:
                        points: [self.x, self.center_y, self.right, self.center_y]
                        width: 1

                MDBoxLayout:
                    spacing: 12
                    size_hint: 1, 1
                    pos_hint: {"center_x": .5, "center_y": .5}

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia1

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "dom"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia2

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "seg"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia3

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "ter"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia4

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "qua"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia5

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "qui"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia6

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "sex"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

                    MDBoxLayout:
                        orientation: "vertical"
                        spacing: 5

                        Widget:

                        Widget:
                            size_hint: None, None
                            width: 20
                            height: root.dia7

                            canvas.before:
                                Color:
                                    rgba: 0.5,0.75,0.68,1

                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [6]

                        MDLabel:
                            text: "sab"
                            halign: "center"
                            font_size: 11
                            size_hint_y: None
                            height: 20

<Ventilador>:
    name: "ventilador"

    MDLabel:
        text: "Tela Ventilador"
        halign: "center"

    MDIconButton:
        icon: "arrow-left"

        on_release:
            app.root.current = "aparelhos"
            app.root.transition.direction = "right"
            
<Ideias>:
    name: "ideias"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)

        MDLabel:
            text: "Economia consciente"
            bold: True
            size_hint_y: None
            height: self.texture_size[1]

        # CARROSSEL DE DICAS
        MDCarousel:
            id: dicas_carousel
            size_hint_y: None
            height: dp(180)

            FitImage:
                source: "Images/dica1.png"
                radius: [20,]

            FitImage:
                source: "Images/dica2.png"
                radius: [20,]

            FitImage:
                source: "Images/dica3.png"
                radius: [20,]

        MDLabel:
            text: "Pontos e recompensas"
            bold: True
            size_hint_y: None
            height: self.texture_size[1]

        # CARDS DESLIZÁVEIS
        ScrollView:
            do_scroll_y: False
            do_scroll_x: True
            size_hint_y: None
            height: dp(140)

            MDBoxLayout:
                adaptive_width: True
                spacing: dp(15)
                padding: [0,0,20,0]

                MDCard:
                    size_hint: None, None
                    size: dp(120), dp(120)
                    radius: [15,]

                    MDBoxLayout:
                        orientation: "vertical"
                        padding: dp(10)

                        MDLabel:
                            text: "Ler dicas"

                        MDLabel:
                            text: "+50 pontos"

                        MDRaisedButton:
                            text: "Resgatar"

                MDCard:
                    size_hint: None, None
                    size: dp(120), dp(120)
                    radius: [15,]

                    MDBoxLayout:
                        orientation: "vertical"
                        padding: dp(10)

                        MDLabel:
                            text: "Economizar"

                        MDLabel:
                            text: "+200 pontos"

                MDCard:
                    size_hint: None, None
                    size: dp(120), dp(120)
                    radius: [15,]

        MDTextButton:
            text: "Ver prêmios"
            pos_hint: {"center_x": .15}

        MDLabel:
            text: "Meus hábitos"
            bold: True
            size_hint_y: None
            height: self.texture_size[1]

        MDRaisedButton:
            text: "▼ maio"
            size_hint: None, None
            size: dp(90), dp(40)
            md_bg_color: .85, .95, .88, 1
            text_color: .4, .7, .5, 1

        MDBoxLayout:
            spacing: dp(20)

            # LADO ESQUERDO
            MDBoxLayout:
                orientation: "vertical"

                MDLabel:
                    text: "Economia mensal"
                    halign: "center"

                Widget:

                MDLabel:
                    text: "X %"
                    halign: "center"

                Widget:

            # LADO DIREITO
            MDBoxLayout:
                orientation: "vertical"

                MDLabel:
                    text: "Total economizado"

                MDLabel:
                    text: "XXX Kw"
                    font_size: "28sp"
                    bold: True

                MDLabel:
                    text: "Rendimento"

                MDChip:
                    text: "Positivo"

        Widget:

        # MENU INFERIOR
        MDBoxLayout:
            size_hint_y: None
            height: dp(60)
            spacing: dp(40)

            Widget:

            MDIconButton:
                icon:
                    "home" if root.manager.current == "home" else "home-outline"

                on_release:
                    root.manager.current = "home"
                    app.root.transition.direction = "right"

            MDIconButton:
                icon: "lightbulb"
                theme_bg_color: "Custom"
                md_bg_color: 0.85,0.75,1,1
                radius: [25,]

            MDIconButton:
                icon: "account"

            Widget: